title: "<%= _('page title|edit microsites') %>"
components:
  - uuid: "microsite_update_form"
    description: ""
    method: PATCH
    title: "<%= _('title|edit microsites') %>"
    type: form
    url: "/v1/admin/system_settings/microsites/<uuid>"
    elements:
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|microsite name') %>"
          name: "title"
          placeholder: "<%= _('plc|microsite name') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.title.too_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.title.too_long') %>"
              type: max
              value: "20"

      - - atom: text
          uuid: "sales_area_ids"
          name: "sales_area_ids"
