title: "Assigned roles of new user"
components:
  - uuid: "user_partners_form"
    description: ""
    method: GET
    title: Show user
    type: form
    url: "/v1/admin/users/<uuid>/partners"
    elements:
      - - atom: hidden
          uuid: "user_uuid"
          label: user_uuid
          name: "user_uuid"
          validation_type: string
          validations:
            - message: "<%= I18n.t('my_message') %>"
              type: required

      - - atom: hidden
          uuid: "function"
          label: Function
          name: "function"
          validation_type: string
          validations:
            - message: "<%= I18n.t('my_message') %>"
              type: required
