title: "Filter"
components:
  - uuid: "filter_users_modal_form"
    description:
    method: GET
    title:
    type: form
    url: "/v1/salesdocs"
    elements:
      - - atom: text
          uuid: 'username'
          label: Username
          name: "username"
          value: ""

      - - atom: text
          uuid: 'first_name'
          label: First name
          name: "first_name"
          value: ""

      - - atom: text
          uuid: 'last_name'
          label: Last name
          name: "last_name"
          value: ""

      - - atom: text
          uuid: 'email'
          label: email
          name: "email"
          value: ""

      - - atom: button
          text: Cancel
          type: text
          action_type: button
          name: "apply"

        - atom: button
          text: Apply
          type: secondary
          action_type: submit
          name: "apply"
