components:
  - uuid: "admin_roles_permissions_destroy_form"
    description:
    method: DELETE
    type: form
    url: "/v1/admin/roles/<role_uuid>/permissions/<permission_id>"
    elements:
      - - atom: hidden
          label: "<%= _('lbl|permission_id') %>"
          name: "id"
          uuid: "id"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.permission_id.blank') %>"
              type: required

        - atom: hidden
          label: "<%= _('lbl|role_uuid') %>"
          name: "role_uuid"
          uuid: "role_uuid"
          validations:
            - message: "<%= _('error|attributes.role_uuid.blank') %>"
              type: required
