title: "<%= _('page title|sales_area maintenance') %>"
components:
  - uuid: "sales_areas_index_form"
    description: ""
    method: GET
    title: "<%= _('page title|sales_area maintenance') %>"
    type: form
    url: ""
    data_url: "/v1/admin/system_settings/sales_areas"
    elements:
      thead:
        - key: true
          name: "title"
          caption: "<%= _('lbl|sales_area title') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"
        - key: true
          name: "description"
          caption: "<%= _('lbl|sales_area description') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "active"
          caption: "<%= _('lbl|sales_area active') %>"
          label: null
          sortable: true
          hidden: false


        - atom: button
          uuid: "cancel"
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        - atom: button
          uuid: "apply"
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit
