title: "Show user"
components:
  - uuid: "users_show_form"
    description: ""
    method: GET
    title: Show user
    type: form
    url: "/v1/admin/users/<uuid>"
    elements:
      - - atom: hidden
          uuid: "uuid"
          label: UUID
          name: "uuid"
          validation_type: string
          validations:
            - message: "<%= I18n.t('my_message') %>"
              type: required
      - - atom: hidden
          uuid: "id"
          label: ID
          name: "id"
          validation_type: string
