title: "<%= _('page title|assignable roles') %>"
components:
  - uuid: "roles_can_assign_of_new_user_form"
    description: ""
    method: PATCH
    title: Show user
    type: form
    url: "/v1/admin/users/<uuid>"
    elements:
      thead:
        - key: true,
          name: 'id'
          uuid: 'id'
          caption: "<%= _('lbl|id') %>"
          label: null
          sortable: true

        - key: true,
          name: 'title'
          uuid: 'title'
          caption: "<%= _('lbl|title') %>"
          label: null
          sortable: true
          action: 'expand'
