title: ""
components:
  - uuid: "sales_areas_new_form"
    description: ""
    method: POST
    title: ""
    type: form
    url: "/v1/admin/system_settings/sales_areas/<uuid>"
    data_url: "/v1/admin/system_settings/sales_areas"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"

      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|description') %>"
          name: "description"

      - - atom: outside_checkbox
          uuid: "active"
          name: "active"
          label: "<%= _('lbl|active') %>"
          placeholder: "<%= _('plc|active') %>"

      - - atom: hidden
          uuid: "doc_type_ids"
          name: "doc_type_ids"
