title: "<%= _('page title|role maintenance') %>"
components:
  - uuid: "roles_list_table"
    description: ""
    method: GET
    title: Assign roles to user
    type: datatable
    url: ""
    data_url: "/v1/admin/roles"
    elements:
      thead:
        - key: true
          name: "title"
          caption: "<%= _('lbl|role name') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"
        - key: true
          name: "description"
          caption: "<%= _('lbl|description') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "created_by"
          caption: "<%= _('lbl|created by') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "active"
          caption: "<%= _('lbl|active') %>"
          datatype: boolean
          label: null
          sortable: true
          hidden: false
