title: "assignable roles of new user"
components:
  - uuid: "territories_of_new_user_form"
    description: ""
    method: PATCH
    title: Show user
    type: form
    url: "/v1/admin/users/<uuid>"
    elements:
      - - atom: hidden
          uuid: "territory_ids"
          label: assigned_roles
          name: "territory_ids"
          validation_type: string
      - - atom: hidden
          uuid: "uuid"
          label: ID
          name: "uuid"
          validation_type: string
