title: "<%= _('page title|sales area doc categories') %>"
components:
  - uuid: "doc_categories_of_sales_area_form"
    description: ""
    method: POST
    title: ""
    type: form
    url: "/v1/admin/system_settings/sales_areas/<uuid>"
    elements:
      thead:
        - key: true
          name: 'id'
          uuid: 'id'
          caption: "<%= _('lbl|id') %>"
          label: null
          sortable: true

        - key: true
          name: 'title'
          uuid: 'title'
          caption: "<%= _('lbl|title') %>"
          label: null
          sortable: true
          action: 'expand'

        - key: true
          name: 'description'
          uuid: 'description'
          caption: "<%= _('lbl|description') %>"
          label: null
          sortable: true
          action: 'expand'

        - key: true
          name: 'created_by'
          uuid: 'created_by'
          caption: "<%= _('lbl|created_by') %>"
          label: null
          sortable: true
          action: 'expand'
