title: "Assignable roles of new user"
components:
  - uuid: "roles_can_assign_of_new_user_form"
    description: ""
    method: PATCH
    title: Show user
    type: form
    url: "/v1/admin/users/<uuid>"
    elements:
      thead:
        - key: true,
          name: 'id'
          uuid: 'id'
          caption: 'Id'
          label: null
          sortable: true
          action: 'expand'

        - key: true,
          name: 'title'
          uuid: 'title'
          caption: 'Titles'
          label: null
          sortable: true
          action: 'expand'
