title: ""
components:
  - uuid: "doc_type_update_form"
    description: ""
    method: PATCH
    title: ""
    type: form
    url: "/v1/admin/system_settings/doc_types/<uuid>"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"

      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|description') %>"
          name: "description"

      - - atom: text
          uuid: "data"
          label: "<%= _('lbl|data') %>"
          name: "data"
