title: "<%= _('page title|sap downtimes maintenance') %>"
components:
  - uuid: "sap_connections_index_form"
    description: ""
    method: GET
    title: ""
    type: form
    url: ""
    data_url: "/v1/admin/system_settings/sap_maintenance/sap_downtimes"
    elements:
      thead:
        - key: true
          name: "title"
          caption: "<%= _('lbl|title') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"
        - key: true
          name: "description"
          caption: "<%= _('lbl|description') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "down_from_date"
          caption: "<%= _('lbl|down from date') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "down_to_date"
          caption: "<%= _('lbl|down to date') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "down_from_time"
          caption: "<%= _('lbl|down from time') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "down_to_time"
          caption: "<%= _('lbl|down to time') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "active"
          caption: "<%= _('lbl|active') %>"
          label: null
          sortable: true
          hidden: false
