title: "Assigned roles of new user"
components:
  - uuid: "assigned_roles"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Assign roles to user
    type: datatable
    name: "role_ids"
    url: "/v1/assigned_roles"
    selected_rows: []
    data_url: "/v1/"
    elements:
      thead:
        - key: true,
          name: 'id'
          uuid: 'id'
          caption: 'Id'
          label: null
          sortable: true
          action: 'expand'

        - key: true,
          name: 'title'
          uuid: 'title'
          caption: 'Titles'
          label: null
          sortable: true
          action: 'expand'
