title: "Assigned roles of new user"
components:
  - uuid: "add_sold_to"
    method: POST
    title: Select sold-to`s
    type: form
    url: "/v1/partners/new"
    elements:
      - - atom: button_with_modal
          text: Add Sold-to
          url: "/v1/partners/new"
          name: "Submit"

