title: "<%= _('page title|role maintenance') %>"
components:
  - uuid: "roles_edit_form"
    description: ""
    method: GET
    title: "<%= _('page title|role maintenance') %>"
    type: form
    url: ""
    data_url: "/v1/admin/roles"
    elements:
      thead:
        - key: true
          name: "title"
          caption: "<%= _('lbl|role name') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"
        - key: true
          name: "description"
          caption: "<%= _('lbl|description') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "created_by"
          caption: "<%= _('lbl|created by') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "active"
          caption: "<%= _('lbl|is active') %>"
          label: null
          sortable: true
          hidden: false

        - atom: button
          uuid: "cancel"
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        - atom: button
          uuid: "apply"
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit