title: "<%= _('page title|user details') %>"
components:
  - uuid: "admin_create_new_user_step_1"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Complete user details
    type: form
    url: "/v1/admin/users"
    elements:
      - - atom: hidden
          uuid: "uuid"
          label: uuid
          name: "uuid"
          validation_type: string
          value: ""

      - - atom: text
          uuid: "username"
          label: "<%= _('lbl|username') %>"
          name: "username"
          placeholder: "<%= _('plc|username') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.username.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.username.too_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.username.too_long') %>"
              type: max
              value: "20"

        - atom: select
          uuid: "user_classification_id"
          label: "<%= _('lbl|user classification') %>"
          name: "user_classification_id"
          placeholder: "<%= _('plc|select user classification') %>"
          validation_type: string
          value: ""
          options:
            - name: "<%= _('lbl|user classification dealer') %>"
              value: 'dealer'
            - name: "<%= _('lbl|user classification distributor') %>"
              value: 'distributor'

      - - atom: text
          uuid: "first_name"
          label: "<%= _('lbl|first name') %>"
          name: "first_name"
          placeholder: "<%= _('plc|first name') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.first_name.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.first_name.to_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.first_name.too_long') %>"
              type: max
              value: "20"
        - atom: text
          uuid: "last_name"
          label: "<%= _('lbl|last name') %>"
          name: "last_name"
          placeholder: "<%= _('plc|last name') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.last_name.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.last_name.to_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.last_name.too_long') %>"
              type: max
              value: "20"

      - - atom: text
          uuid: "email"
          label: "<%= _('lbl|email address') %>"
          name: "email"
          placeholder: "<%= _('plc|email address') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.email.blank') %>"
              type: required
              value: ""

        - atom: text
          uuid: "phone"
          label: "<%= _('lbl|phone') %>"
          name: "phone"
          placeholder: "<%= _('plc|phone') %>"
          validation_type: string
          value: ""

      - - atom: text
          uuid: "password"
          label: "<%= _('lbl|password') %>"
          name: "password"
          placeholder: "<%= _('plc|password') %>"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.password.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.password.confirmation') %>"
              type: confirmation

        - atom: text
          uuid: "password_confirmation"
          label: "<%= _('lbl|password confirmation') %>"
          name: "password_confirmation"
          placeholder: "<%= _('plc|password confirmation') %>"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.password_confirmation.blank') %>"
              type: required
              value: ""

      - - atom: select
          uuid: "microsite_id"
          label: "<%= _('lbl|microsite') %>"
          name: "microsite_id"
          placeholder: "<%= _('plc|microsite') %>"
          validation_type: string
          value: ""
          options:
            - name: Microsite 1
              value: "1"
          validations:
            - message: "<%= _('error|attributes.microsite.blank') %>"
              type: required
              value: ""

      - - atom: select
          uuid: "user_type_id"
          label: "<%= _('lbl|user type') %>"
          name: "user_type_id"
          placeholder: "<%= _('plc|user type') %>"
          validation_type: string
          value: ""
          options:
            - name: CT 1
              value: "1"
            - name: CT 2
              value: "2"
          validations:
            - message: "<%= _('error|attributes.user_type.blank') %>"
              type: required
              value: ""

        - atom: select
          uuid: "language"
          label: "<%= _('lbl|language') %>"
          name: "language"
          placeholder: "<%= _('plc|select language') %>"
          validation_type: string
          value: "pl_PL"
          options:
            - name: "<%= _('lbl|language en_US') %>"
              value: "en_US"
            - name: "<%= _('lbl|language pl_PL') %>"
              value: "pl_PL"
          validations:
            - message: "<%= _('error|attributes.language.blank') %>"
              type: required
              value: ""

        - atom: select
          uuid: "time_zone"
          label: "<%= _('lbl|time zone') %>"
          name: "time_zone"
          placeholder: "<%= _('plc|select time zone') %>"
          validation_type: string
          value: ""
          options:
            - name: "<%= _('lbl|time zone UTC') %>"
              value: 'utc'
            - name: "<%= _('lbl|time zone EST') %>"
              value: 'est'
          validations:
            - message: "<%= _('error|attributes.time_zone.blank') %>"
              type: required
              value: ""

      - - atom: select
          uuid: "number_format"
          label: "<%= _('lbl|number format') %>"
          name: "number_format"
          placeholder: "<%= _('plc|select number format') %>"
          validation_type: string
          value: ""
          options:
            - name: "9,999,999.99"
              value: ".,"
            - name: "9.999.999,99"
              value: ",."
            - name: "9'999'999.99"
              value: "."
          validations:
            - message: "<%= _('error|attributes.number_format.blank') %>"
              type: required
              value: ""

        - atom: select
          uuid: "date_format"
          label: "<%= _('lbl|date format') %>"
          name: "date_format"
          placeholder: "<%= _('plc|select date format') %>"
          validation_type: string
          value: ""
          options:
            - name: English
              value: en_US
          validations:
            - message: "<%= _('error|attributes.date_format.blank') %>"
              type: required
              value: ""

        - atom: select
          uuid: "time_format"
          label: "<%= _('lbl|time format') %>"
          name: "time_format"
          placeholder: "<%= _('plc|select time format') %>"
          validation_type: string
          value: ""
          options:
            - name: 24h
              value: '%H:%M:%S'
            - name: 12h
              value: '%I:%M:%S %p'
          validations:
            - message: "<%= _('error|attributes.time_format.blank') %>"
              type: required
              value: ""

      - - atom: button
          uuid: "button_1"
          text: "<%= _('btn|next') %>"
          type: primary
          action_type: submit
