title: "Sold tos of new user"
components:
  - uuid: "sold_tos_of_new_user_form"
    description: ""
    method: PATCH
    title: Show user
    type: form
    url: "/v1/admin/users?step=4"
    elements:
      - - atom: hidden
          uuid: "partners"
          label: assigned_roles
          name: "partners"
          validation_type: string

      - - atom: hidden
          uuid: "uuid"
          label: ID
          name: "uuid"
          validation_type: string
