title: "<%= _('page title|assigned roles') %>"
components:
  - uuid: "assigned_roles"
    method: POST
    title: ""
    type: datatable
    name: "role_ids"
    url: "/v1/assigned_roles"
    data_url: "/v1/"
    elements:
      thead:
        - key: true,
          name: 'id'
          uuid: 'id'
          caption: "<%= _('lbl|id') %>"
          label: null
          sortable: true

        - key: true,
          name: 'title'
          uuid: 'title'
          caption: "<%= _('lbl|title') %>"
          label: null
          sortable: true
          action: 'expand'
