title: "<%= _('page title|edit sap downtime') %>"
components:
  - uuid: "sap_downtime_edit_form"
    description: ""
    method: POST
    title: ""
    type: form
    url: "/v1/admin/system_settings/sap_maintenance/sap_downtimes"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"
          label: "<%= _('lbl|uuid') %>"

      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "description"
          name: "description"
          label: "<%= _('lbl|description') %>"
          placeholder: "<%= _('plc|description') %>"

      - - atom: outside_checkbox
          uuid: "active"
          name: "active"
          label: "<%= _('lbl|active') %>"
          placeholder: "<%= _('plc|active') %>"

      - - atom: date
          uuid: "down_from_date"
          name: "down_from_date"
          label: "<%= _('lbl|down from date') %>"
          placeholder: "<%= _('plc|down from date') %>"
          validations:
            - message: "<%= _('error|attributes.down_from_date.blank') %>"
              type: required
              value: ""

        - atom: time
          uuid: "down_from_time"
          name: "down_from_time"
          label: "<%= _('lbl|down from time') %>"
          placeholder: "<%= _('plc|down from time') %>"
          validations:
            - message: "<%= _('error|attributes.down_from_time.blank') %>"
              type: required
              value: ""

      - - atom: date
          uuid: "down_to_date"
          name: "down_to_date"
          label: "<%= _('lbl|down to date') %>"
          placeholder: "<%= _('plc|down to date') %>"
          validations:
            - message: "<%= _('error|attributes.down_to_date.blank') %>"
              type: required
              value: ""

        - atom: time
          uuid: "down_to_time"
          name: "down_to_time"
          label: "<%= _('lbl|down to time') %>"
          placeholder: "<%= _('plc|down to time') %>"
          validations:
            - message: "<%= _('error|attributes.down_to_time.blank') %>"
              type: required
              value: ""

#      - - atom: timezone
#          uuid: "timezone"
#          name: "timezone"
#          label: "<%= _('lbl|timezone') %>"
#          placeholder: "<%= _('plc|timezone') %>"
#          validations:
#            - message: "<%= _('error|attributes.timezone.blank') %>"
#              type: required
#              value: ""
