title: "<%= _('page title|new sales area') %>"
components:
  - uuid: "sales_areas_new_form"
    description: ""
    method: POST
    title: "<%= _('title|new sales area') %>"
    type: form
    url: "/v1/admin/system_settings/sales_areas/<uuid>"
    data_url: "/v1/admin/system_settings/sales_areas"
    elements:
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|description') %>"
          name: "description"

      - - atom: text
          uuid: "active"
          label: "<%= _('lbl|active') %>"
          name: "active"

      - - atom: hidden
          uuid: "doc_type_ids"
          name: "doc_type_ids"
