title: "<%= _('page title|sales area maintenance') %>"
components:
  - uuid: "sales_areas_index_form"
    description: ""
    method: GET
    title: "<%= _('title|sales area maintenance') %>"
    type: form
    url: ""
    data_url: "/v1/admin/system_settings/sales_areas"
    elements:
      thead:
        - key: true
          name: "title"
          caption: "<%= _('lbl|title') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"

        - key: true
          name: "description"
          caption: "<%= _('lbl|description') %>"
          label: null
          sortable: true
          hidden: false

        - key: true
          name: "active"
          caption: "<%= _('lbl|active') %>"
          datatype: boolean
          label: null
          sortable: true
          hidden: false
