title: "<%= _('page title|new doc_type') %>"
components:
  - uuid: "doc_types_edit_form"
    description: ""
    method: GET
    title: ""
    type: form
    url: ""
    data_url: "/v1/admin/system_settings/doc_types"
    elements:
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|description') %>"
          name: "description"
          validation_type: string

      - - atom: textarea
          uuid: "data"
          label: "<%= _('lbl|data') %>"
          name: "data"
          validation_type: string
