title: "<%= _('page title|update sales_area') %>"
components:
  - uuid: "sales_area_update_form"
    description: "<%= _('page title|update sales_area') %>"
    method: POST
    title: "<%= _('page title|update sales_area') %>"
    type: form
    url: "/v1/admin/system_settings/sales_areas/"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|sales_area title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""
      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|sales_area description') %>"
          name: "description"
      - - atom: text
          uuid: "active"
          label: "<%= _('lbl|sales_area active') %>"
          name: "active"
      - - atom: text
          uuid: "doc_types"
          name: "doc_types"
