title: "<%= _('page title|update role') %>"
components:
  - uuid: "role_update_form"
    description: "<%= _('page title|update role') %>"
    method: GET
    title: "<%= _('page title|update role') %>"
    type: form
    url: "/v1/admin/roles/<role_uuid>"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|role title') %>"
          name: "title"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""
      - - atom: text
          uuid: "description"
          label: "<%= _('lbl|role description') %>"
          name: "description"
      - - atom: text
          uuid: "permissions"
          name: "permissions"