title: "<%= _('page title|edit translation') %>"
components:
  - uuid: "edit_translation_form"
    description: ""
    method: PATCH
    title: "<%= _('title|edit translation') %>"
    type: form
    url: "/v1/admin/translations/"
    elements:
      - - atom: text
          uuid: "key"
          label: "<%= _('lbl|key') %>"
          name: "key"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.key.blank') %>"
              type: required
              value: ""

      - - atom: select
          uuid: "locale"
          label: "<%= _('lbl|locale') %>"
          name: "locale"
          options:
            - name: "<%= _('lbl|language en_US') %>"
              value: "en_US"
            - name: "<%= _('lbl|language es_ES') %>"
              value: "es_ES"
            - name: "<%= _('lbl|language ru_RU') %>"
              value: "ru_RU"

      - - atom: text
          uuid: "cst_translation"
          label: "<%= _('lbl|cst_translation') %>"
          name: "cst_translation"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.cst_translation.blank') %>"
              type: required
              value: ""


      - - atom: text
          uuid: "status"
          label: "<%= _('lbl|status') %>"
          name: "status"
          validation_type: string

      - - atom: select
          uuid: "microsite_id"
          label: "<%= _('lbl|microsite') %>"
          name: "microsite_id"
          validation_type: string
          options:
            - name: Microsite 1
              value: "1"
            - name: Microsite 2
              value: "2"

      - - atom: button
          uuid: "cancel"
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        - atom: button
          uuid: "apply"
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit
