title: "<%= _('page title|create microsites') %>"
components:
  - uuid: "microsite_create_form"
    description: "<%= _('page title|create microsites') %>"
    method: GET
    title: "<%= _('page title|create microsites') %>"
    type: form
    url: "/v1/admin/system_settings/microsites/"
    elements:
      - - atom: text
          uuid: "title"
          label: "<%= _('lbl|title') %>"
          name: "username"
          placeholder: "<%= _('plc|title') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.title.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.title.too_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.title.too_long') %>"
              type: max
              value: "20"
      - - atom: text
          uuid: "sales_areas"
          name: "sales_areas"
