title: "<%= _('page title|new user') %>"
components:
  - uuid: "step 1"
    method: GET
    title: "<%= _('title|user details') %>"
    type: step
    data_url: "/v1/admin/users/new?step=1"

  - uuid: "step 2"
    method: GET
    title: "<%= _('title|assigned roles') %>"
    type: step
    data_url: "/v1/admin/users/new?step=2"

  - uuid: "step 3"
    method: GET
    title: "<%= _('title|assignable roles') %>"
    type: step
    data_url: "/v1/admin/users/new?step=3"

  - uuid: "step 4"
    method: GET
    title: "<%= _('title|sold tos') %>"
    type: step
    data_url: "/v1/admin/users/new?step=4"

  - uuid: "step 5"
    method: GET
    title: "<%= _('title|ship tos') %>"
    type: step
    data_url: "/v1/admin/users/new?step=5"

  - uuid: "step 6"
    method: GET
    title: "<%= _('title|territories') %>"
    type: step
    data_url: "/v1/admin/users/new?step=6"
