title: "User maintenance"
components:
  - uuid: "users_list_table"
    description: ""
    method: GET
    title: Assign roles to user
    type: datatable
    url: ""
    data_url: "/v1/admin/users"
    elements:
      thead:
        - key: true
          name: "username"
          caption: "<%= _('lbl|username') %>"
          label: null
          sortable: true
          hidden: false
          action: "link"
        - key: true
          name: "first_name"
          caption: "<%= _('lbl|first name') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "last_name"
          caption: "<%= _('lbl|last name') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "email"
          caption: "<%= _('lbl|email address') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: "phone"
          caption: "<%= _('lbl|phone') %>"
          label: null
          sortable: false
          hidden: false
        - key: true
          name: "language"
          caption: "<%= _('lbl|locale') %>"
          label: null
          sortable: false
          hidden: true
        - key: true
          name: "active"
          caption: "<%= _('lbl|active') %>"
          datatype: boolean
          label: null
          sortable: true
          hidden: true
