title: "Edit a user"
components:
  - uuid: "search_salesdoc_table"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Select sold-to`s
    type: datatable
    url: "/v1/partners"
    elements:
      thead:
        - key: true
          name: 'number'
          caption: 'Sold-to number'
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'name'
          caption: 'Name'
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_1'
          caption: 'Postal Address 1'
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_2'
          caption: 'Postal Address 2'
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_3'
          caption: 'Postal Address 3'
          label: null
          sortable: true
          hidden: false
        - name: 'country'
          caption: 'Country code'
          label: null
          sortable: true
          hidden: false
        - name: 'sales_area_id'
          caption: 'Sales area ID'
          label: null
          sortable: true
          hidden: false
        - name: 'action'
          caption: 'Action'
          label: null
          sortable: false
          hidden: false
          row_action: "delete"
          type_btn: "link"
          icon: 'trash'
