title: "<%= _('page title|assigned partners') %>"
components:
  - uuid: "search_salesdoc_table"
    description: ""
    method: POST
    title: Select ship-to`s
    type: datatable
    url: "/v1/partners"
    elements:
      thead:
        - key: true
          name: 'number'
          caption: "<%= _('lbl|partner WE number') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'name'
          caption: "<%= _('lbl|partner name') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_1'
          caption: "<%= _('lbl|postal address 1') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_2'
          caption: "<%= _('lbl|postal address 2') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'postal_address_3'
          caption: "<%= _('lbl|postal address 3') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'country'
          caption: "<%= _('lbl|country') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'sales_area_id'
          caption: "<%= _('lbl|sales area id') %>"
          label: null
          sortable: true
          hidden: false
        - name: 'action'
          caption: "<%= _('lbl|actions') %>"
          label: null
          sortable: false
          hidden: false
          row_action: "delete"
          type_btn: "link"
          icon: 'trash'
