title: "Create new user"
components:
  # Components for user create page. The entire multiform widget
  - uuid: "create_new_user_multi_step_form"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Create New user
    type: multiform
    url: "/v1/admin/users"

    # Components of multiform widget. Steps in the left menu of the widget
    components:
      - uuid: "1"
        description: ""
        method: "POST"
        title: User details
        type: step
        url: "?step=1"

        # Components from one step of multiform.
        components:
          - uuid: "admin_create_new_user_step_1"
            description: "Fields with an asterisk (*) are mandatory."
            method: POST
            title: Complete user details
            type: form
            url: "/v1/admin/users"
            elements:
              - - atom: text
                  uuid: "username"
                  label: User ID
                  name: "username"
                  placeholder: User ID
                  validation_type: string
                  value: ""
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""
                    - message: "User ID cannot be less than 3 characters"
                      type: min
                      value: "3"
                    - message: "User ID cannot be more than 20 characters"
                      type: max
                      value: "20"

                - atom: select
                  uuid: "user_classification_id"
                  label: Customer Type
                  name: "user_classification_id"
                  placeholder: Select Customer Type
                  validation_type: string
                  value: ""
                  options:
                    - name: Dealer
                      value: 'Dealer'
                    - name: Distributor
                      value: 'Distributor'

              - - atom: text
                  uuid: "first_name"
                  label: First name
                  name: "first_name"
                  placeholder: First name
                  validation_type: string
                  value: ""
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""
                    - message: "First Name cannot be less than 3 characters"
                      type: min
                      value: "3"
                    - message: "First Name cannot be more than 20 characters"
                      type: max
                      value: "20"
                - atom: text
                  uuid: "last_name"
                  label: Last name
                  name: "last_name"
                  placeholder: Last name
                  validation_type: string
                  value: ""
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""
                    - message: "Last name cannot be less than 3 characters"
                      type: min
                      value: "3"
                    - message: "Last name cannot be more than 20 characters"
                      type: max
                      value: "20"

              - - atom: text
                  uuid: "email"
                  label: Email address
                  name: "email"
                  placeholder: Email address
                  validation_type: string
                  value: ""
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

                - atom: text
                  uuid: "phone"
                  label: Phone Number
                  name: "phone"
                  placeholder: Phone
                  validation_type: string
                  value: ""

              - - atom: text
                  uuid: "password"
                  label: Password
                  name: "password"
                  placeholder: Password
                  validation_type: string
                  validations:
                    - message: " field is required"
                      type: required
                    - message: "password should match password confirmation"
                      type: confirmation

                - atom: text
                  uuid: "password_confirmation"
                  label: Password confirmation
                  name: "password_confirmation"
                  placeholder: Password confirmation
                  validation_type: string
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required

              - - atom: select
                  uuid: "microsite_id"
                  label: Microsite
                  name: "microsite_id"
                  placeholder: Select Microsite
                  validation_type: string
                  value: ""
                  options:
                    - name: Microsite 1
                      value: 'b2b_microsite1'
                    - name: Microsite 2
                      value: 'b2b_client'
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

              - - atom: select
                  uuid: "user_type_id"
                  label: Customer Type
                  name: "user_type_id"
                  placeholder: Select Customer Type
                  validation_type: string
                  value: ""
                  options:
                    - name: CT 1
                      value: 'customer_type_1'
                    - name: CT 2
                      value: 'customer_type_2'
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""
                - atom: select
                  uuid: "language"
                  label: Language
                  name: "language"
                  placeholder: Select Language
                  validation_type: string
                  value: "pl_PL"
                  options:
                    - name: English
                      value: en_US
                    - name: Polish
                      value: pl_PL
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

                - atom: select
                  uuid: "time_zone"
                  label: Timezone
                  name: "time_zone"
                  placeholder: Select Timezone
                  validation_type: string
                  value: ""
                  options:
                    - name: Microsite 1
                      value: 'b2b_microsite1'
                    - name: Microsite 2
                      value: 'b2b_client'
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

              - - atom: select
                  uuid: "number_format"
                  label: Number Format
                  name: "number_format"
                  placeholder: Select Number Format
                  validation_type: string
                  value: ""
                  options:
                    - name: Microsite 1
                      value: 'b2b_microsite1'
                    - name: Microsite 2
                      value: 'b2b_client'
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

                - atom: select
                  uuid: "date_format"
                  label: Date Format
                  name: "date_format"
                  placeholder: Select Date Format
                  validation_type: string
                  value: ""
                  options:
                    - name: English
                      value: en_US
                    - name: Polish
                      value: pl_PL
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

                - atom: select
                  uuid: "time_format"
                  label: Time Format
                  name: "time_format"
                  placeholder: Select Time Format
                  validation_type: string
                  value: ""
                  options:
                    - name: Microsite 1
                      value: 'b2b_microsite1'
                    - name: Microsite 2
                      value: 'b2b_client'
                  validations:
                    - message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""

              - - atom: hidden
                  uuid: "uuid"
                  label: User ID
                  name: "uuid"
                  value: ""

              - - atom: button
                  uuid: "button_1"
                  text: Next
                  type: primary
                  action_type: submit
                  name: "Submit"

      - uuid: "2"
        description: ""
        method: "POST"
        title: Assigned roles
        type: step
        url: "?step=2"

        # Components from one step of multiform.
        components:
          - uuid: "assigned_roles"
            description: "Fields with an asterisk (*) are mandatory."
            method: POST
            title: Assign roles to user
            type: datatable
            url: "/v1/assigned_roles"
            elements:
              thead:
                - key: true,
                  name: 'role'
                  caption: 'Role'
                  label: null
                  sortable: true
                  action: 'expand'

              rows:
                - "role": "administration"
                - "role": "all but admin"
                - "role": "Change Order"
                - "role": "Create Order"
