title: "<%= _('page title|simulate cart') %>"
components:
  - uuid: "cart_simulate_form"
    description: "<%= _('page title|simulate cart') %>"
    method: POST
    title: "<%= _('page title|simulate cart') %>"
    type: form
    url: "/v1/carts/simulate"
    elements:
      - - atom: hidden
          uuid: "doc_type"
          name: "doc_type"

      - - atom: hidden
          uuid: "sales_area"
          name: "sales_area"
          
      - - atom: hidden
          uuid: "rdd"
          name: "rdd"

      - - atom: hidden
          uuid: "po_number"
          name: "po_number"

      - - atom: text
          uuid: "items"
          name: "items"
          
      - - atom: text
          uuid: "partners"
          name: "partners"
