title: "<%= _('page title|update cart') %>"
components:
  - uuid: "cart_update_form"
    description: "<%= _('page title|update cart') %>"
    method: POST
    title: "<%= _('page title|update cart') %>"
    type: form
    url: "/v1/carts/<uuid>/update"
    elements:
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"
          
      - - atom: hidden
          uuid: "doc_type"
          name: "doc_type"

      - - atom: hidden
          uuid: "sales_area"
          name: "sales_area"
          
      - - atom: hidden
          uuid: "rdd"
          name: "rdd"

      - - atom: hidden
          uuid: "po_number"
          name: "po_number"

      - - atom: text
          uuid: "items"
          name: "items"
          
      - - atom: text
          uuid: "partners"
          name: "partners"
