title: "<%= _('page title|update cart item') %>"
components:
  - uuid: "cart_item_update_form"
    description: "<%= _('page title|update cart item') %>"
    method: POST
    title: "<%= _('page title|update cart item') %>"
    type: form
    url: "/v1/carts/<cart_uuid>/items/"
    elements:
      - - atom: hidden
          uuid: "cart_uuid"
          name: "cart_uuid"
      
      - - atom: hidden
          uuid: "uuid"
          name: "uuid"
          
      - - atom: text
          uuid: "material"
          name: "material"

      - - atom: text
          uuid: "quantity"
          name: "quantity"
          
      - - atom: text
          uuid: "rdd"
          name: "rdd"
