title: "Filter"
components:
  - uuid: "filter_invoices_modal_form"
    description:
    method: GET
    title:
    type: form
    url: "/v1/invoices"
    elements:
      - - atom: select
          uuid: 'search_criteria'
          label: Search Criteria
          name: "search_criteria"
          placeholder: Select Search Criteria
          validation_type: string
          value: "po_number"
          options:
            - name: PO number
              value: 'po_number'
            - name: Material number
              value: 'material'
            - name: Order number
              value: 'salesdoc_number'
            - name: Payer number
              value: 'payer'
            - name: Delivery number
              value: 'delivery_number'

        - atom: text
          uuid: 'search_criteria_value'
          label: Search Criteria Value
          name: "search_criteria_value"
          value: ""

      - - atom: text
          uuid: 'from_date'
          label: From date
          name: "from_date"
          value: ""

        - atom: text
          uuid: 'to_date'
          label: To date
          name: "to_date"
          value: ""

      - - atom: button
          uuid: 'cancel'
          text: Cancel
          type: text
          action_type: button
          action_func: handleFilterCancel

        - atom: button
          uuid: 'apply'
          text: Apply
          type: secondary
          action_type: submit
