title: "List invoices"
components:
  - uuid: "invoice_filter_form"
    description: "Fields with an asterisk (*) are mandatory."
    method: GET
    title: Invoices search criteria
    type: form
    url: "/v1/invoices"
    elements:
      - atom: text
        uuid: "po_number"
        label: PO number
        name: "po_number"
        validation_type: string
        value: ""
      - atom: text
        uuid: "payer"
        label: Payer
        name: "payer"
        validation_type: string
        value: ""
      - atom: text
        uuid: "from_date"
        label: From date
        name: "from_date"
        validation_type: string
        value: ""
      - atom: text
        uuid: "to_date"
        label: To date
        name: "to_date"
        validation_type: string
        value: ""
      - atom: select
        uuid: "status"
        label: Status
        name: "status"
        placeholder: Select status
        validation_type: string
        value: ""
        options:
          - name: Outstanding
            value: outstanding
          - name: Status 2
            value: status_2
          - name: Status 3
            value: status_3
