title: "Set new password"
components:
  - uuid: "forgot_password_2_form"
    description: ""
    method: PATCH
    title: Forgot your password
    type: form
    url: "/v1/password"
    elements:
      - - atom: text
          uuid: "password"
          label: "<%= _('lbl|new password') %>"
          name: "password"
          placeholder: "<%= _('plc|new password') %>"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.new_password.blank') %>"
              type: required

      - - atom: text
          uuid: "password_confirmation"
          label: "<%= _('lbl|confirm password') %>"
          name: "password_confirmation"
          placeholder: "<%= _('plc|confirm password') %>"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.password_confirmation.blank') %>"
              type: required
      - - atom: hidden
          uuid: "reset_password_token"
          name: "reset_password_token"
          value: "<%= @object&.reset_password_token %>"
          validation_type: string
          validations:
            - message: "<%= _('error|attributes.reset_password_token.blank') %>"
              type: required

      - - atom: button
          uuid: "Submit"
          text: "btn|update password"
          type: primary
          action_type: submit
