forgot_password_1:
  title: "Set new password"
  components:
    -
      uuid: "forgot_password_1_form"
      description: ""
      method: PATCH
      title: Forgot your password
      type: form
      url: "/api/v1/password"
      elements:
        -
          -
            atom: text
            label: Password
            name: "user[password]"
            placeholder: Password
            validation_type: string
            validations:
              -
                message: "<%= I18n.t('my_message') %>"
                type: required

        -
          -
            atom: text
            label: Password confirmation
            name: "user[password_confirmation]"
            placeholder: Password confirmation
            validation_type: string
            validations:
              -
                message: "<%= I18n.t('my_message') %>"
                type: required

        -
          -
            atom: button
            text: Login
            type: submit
