title: "Set new password"
components:
  -
    uuid: "forgot_password_1_form"
    description: ""
    method: PATCH
    title: Forgot your password
    type: form
    url: "/api/v1/password"
    elements:
      -
        -
          atom: text
          label: Password
          name: "password"
          placeholder: Password
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required

      -
        -
          atom: text
          label: Password confirmation
          name: "password_confirmation"
          placeholder: Password confirmation
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required
        -
          atom: hidden
          name: "reset_token"
          value: "<%= @object.reset_password_token %>"
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required

      -
        -
          atom: button
          text: Login
          type: submit
