title: "Forgot password page"
components:
  -
    uuid: "forgot_password_1_form"
    description: "Please enter your User ID and we will retrieve your Reset Password Question. If you do not remember your User ID, please send an email to :helpdesk."
    method: POST
    title: Forgot your password
    type: form
    url: "/v1/password"
    elements:
      -
        -
          atom: text
          uuid: "username"
          label: Username
          name: "username"
          placeholder: Username
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required

      -
        -
          atom: button
          uuid: "Submit"
          text: Reset Password
          type: primary
          action_type: submit
