forgot_password_1:
  title: "Forgot password page"
  components:
    -
      forgot_password_1_form:
        description: "Please enter your User ID and we will retrieve your Reset Password Question. If you do not remember your User ID, please send an email to :helpdesk."
        method: POST
        title: Forgot your password
        type: form
        url: "/api/v1/password"
        elements:
          -
            -
              atom: text
              label: Username
              name: "user[username]"
              placeholder: Username
              validation_type: string
              validations:
                -
                  message: "<%= I18n.t('my_message') %>"
                  type: required

          -
            -
              atom: button
              text: Login
              type: submit
