title: "Set new password"
components:
  -
    uuid: "forgot_password_2_form"
    description: ""
    method: PATCH
    title: Forgot your password
    type: form
    url: "/v1/password"
    elements:
      -
        -
          atom: text
          uuid: "password"
          label: Password
          name: "password"
          placeholder: Password
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required

      -
        -
          atom: text
          uuid: "password_confirmation"
          label: Password confirmation
          name: "password_confirmation"
          placeholder: Password confirmation
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required
      -
        -
          atom: hidden
          uuid: "reset_password_token"
          name: "reset_password_token"
          value: "<%= @object&.reset_password_token %>"
          validation_type: string
          validations:
            -
              message: "<%= I18n.t('my_message') %>"
              type: required

      -
        -
          atom: button
          uuid: "Submit"
          text: Update Password
          type: primary
          action_type: submit
