title: "Forgot password page"
components:
  -
    uuid: "forgot_password_1_form"
    description: "Please enter your User ID and we will retrieve your Reset Password Question. If you do not remember your User ID, please send an email to :helpdesk."
    method: POST
    title: "<%= _('title|reset password') %>"
    type: form
    url: "/v1/password"
    elements:
      -
        -
          atom: text
          uuid: "username"
          label: "<%= _('lbl|username') %>"
          name: "username"
          placeholder: "<%= _('plc|username') %>"
          validation_type: string
          validations:
            -
              message: "<%= _('error|attributes.username.blank') %>"
              type: required
              value: ""

      -
        -
          atom: button
          uuid: "reset password"
          text: "<%= _('btn|reset password') %>"
          type: primary
          action_type: submit
