title: "Search for salesdoc"
components:
  - uuid: "search_invoice_table"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Assign roles to user
    type: datatable
    name: "role_ids"
    url: "/v1/assigned_roles"
    selected_rows: []
    data_url: "/v1/"
    elements:
      - key: true
        name: 'number'
        caption: 'Invoice'
        label: null
        sortable: true
        action: 'expand'
      - key: true
        name: 'due_date'
        caption: 'Due date'
        label: null
        sortable: true
        action: 'expand'
      - key: true
        name: 'po_number'
        caption: 'PO'
        label: null
        sortable: true
        action: 'expand'
      - key: true
        name: 'order_number'
        caption: 'Order'
        label: null
        sortable: true
        action: 'expand'
      - key: true
        name: 'total_value'
        caption: 'Total'
        label: null
        sortable: true
        action: 'expand'
