title: "<%= _('page title|search for invoice') %>"
components:
  - uuid: "search_invoice_table"
    description: "Fields with an asterisk (*) are mandatory."
    title: Assign roles to user
    type: datatable
    data_url: "/v1/invoices/search"
    elements:
      thead:
        - key: true
          name: 'doc_number'
          caption: "<%= _('lbl|invoice') %>"
          label: null
          sortable: true
          hidden: false
          action: 'expand'
        - key: true
          name: 'billing_date'
          caption: "<%= _('lbl|due date') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'po_number'
          caption: "<%= _('lbl|po') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'sales_order'
          caption: "<%= _('lbl|order number') %>"
          label: null
          sortable: true
          hidden: false
          action: 'expand'
        - key: true
          name: 'net_value'
          caption: "<%= _('lbl|net value') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'payer_number'
          caption: "<%= _('lbl|payer') %>"
          label: null
          sortable: true
          hidden: true
        - key: true
          name: 'payer_description'
          caption: "<%= _('lbl|payer name') %>"
          label: null
          sortable: true
          hidden: true
        - key: true
          name: 'doc_type'
          caption: "<%= _('lbl|doc type') %>"
          label: null
          sortable: true
          hidden: true
