title: "Invoice"
components:
  - uuid: "salesdoc_items_table"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Assign roles to user
    type: datatable
    name: "role_ids"
    url: "/v1/assigned_roles"
    selected_rows: []
    data_url: "/v1/"
    elements:
      thead:
        - key: true
          name: 'item_number'
          caption: 'Item Number'
          label: null
          sortable: true
        - key: true
          name: 'material'
          caption: 'Material'
          label: null
          sortable: true
        - key: true
          name: 'description'
          caption: 'Description'
          label: null
          sortable: true
        - key: true
          name: 'rdd'
          caption: 'Req. Del Date'
          label: null
          sortable: true
        - key: true
          name: 'net_value'
          caption: 'Net Value'
          label: null
          sortable: true
        - key: true
          name: 'quantity'
          caption: 'Quantity'
          label: null
          sortable: true
        - key: true
          name: 'sales_uom'
          caption: 'Sales UOM'
          label: null
          sortable: true
        - key: true
          name: 'item_cat'
          caption: 'Item Cat.'
          label: null
          sortable: true
        - key: true
          name: 'net_price'
          caption: 'Net Price'
          label: null
          sortable: true
        - key: true
          name: 'per'
          caption: 'Per.'
          label: null
          sortable: true

