title: "<%= _('title|filter') %>"
components:
  - uuid: "filter_invoices_modal_form"
    description:
    method: GET
    title: "<%= _('title|filter') %>"
    type: form
    url: "/v1/invoices"
    elements:
      - - atom: select
          uuid: "search_criteria"
          label: "<%= _('lbl|search criteria') %>"
          name: "search_criteria"
          placeholder: "<%= _('plc|select search criteria') %>"
          validation_type: string
          value: "po_number"
          options:
            - name: "<%= _('lbl|po number') %>"
              value: "po_number"
            - name: "<%= _('lbl|material number') %>"
              value: "material"
            - name: "<%= _('lbl|order number') %>"
              value: "salesdoc_number"
            - name: "<%= _('lbl|payer number') %>"
              value: "payer"
            - name: "<%= _('lbl|delivery number') %>"
              value: "delivery_number"

        - atom: text
          uuid: "search_criteria_value"
          label: "<%= _('lbl|search criteria value') %>"
          name: "search_criteria_value"
          value: ""

      - - atom: date
          uuid: "from_date"
          label: "<%= _('lbl|from date') %>"
          name: "from_date"
          value: ""

        - atom: date
          uuid: "to_date"
          label: "<%= _('lbl|to date') %>"
          name: "to_date"
          value: ""

      - - atom: button
          uuid: "cancel"
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        - atom: button
          uuid: "apply"
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit
