login:
  components:
    -
      login_form:
        -
          description: "Please enter username and password"
          elements:
            -
              group_1:
                -
                  atom: text
                  label: Username
                  name: "user[username]"
                  placeholder: Username
                  validation_type: string
                  validations:
                    -
                      message: "<%= I18n.t('my_message') %>"
                      type: required
                      value: ""
                    -
                      message: "First Name cannot be less than 3 characters"
                      type: min
                      value: "3"
                    -
                      message: "First Name cannot be more than 20 characters"
                      type: max
                      value: "20"
                  value: ""
            -
              group_2:
                -
                  atom: password
                  label: Password
                  name: "user[password]"
                  placeholder: Password
                  validation_type: string
                  validations:
                    -
                      message: "First Name field is required"
                      type: required
                      value: ""
                    -
                      message: "First Name cannot be less than 3 characters"
                      type: min
                      value: "3"
                    -
                      message: "First Name cannot be more than 20 characters"
                      type: max
                      value: "20"
                  value: ""
            -
              group_3:
                -
                  atom: button
                  text: Login
                  type: submit
                -
                  atom: link
                  button_like: "false"
                  path: /forgot_password
                  text: "Forgot your password?"
            -
              group_4:
                -
                  atom: link
                  button_like: "true"
                  path: /registration
                  text: "Create an account"
          method: POST
          title: Login
          type: form
          url: "/api/v1/auth"
  title: "Login page"
