title: "Pay Invoice"
components:
  - uuid: "invoice_payment_form"
    method: POST
    type: form
    url: "/v1/auth"
    elements:
      - - atom: select
          uuid: "payment_method"
          label: Payment Method
          name: "payment_method"
          placeholder: Select Payment Method
          validation_type: string
          value: "c"
          options:
            - name: Credit card
              value: 'c'
            - name: Delego
              value: 'd'
            - name: eCheck
              value: 'e'
          validations:
            - message: "<%= I18n.t('my_message') %>"
              type: required
              value: ""

        - atom: text
          uuid: "reference"
          label: Reference
          name: "reference"
          placeholder: Reference
          validation_type: string
          value: "test"
          validations:
            - message: "Reference field is required"
              type: required
              value: ""
            - message: "Reference cannot be less than 3 characters"
              type: min
              value: "3"
            - message: "Reference cannot be more than 20 characters"
              type: max
              value: "20"

        - atom: button
          text: "<%= _('btn|submit') %>"
          type: secondary
          action_type: submit

        - thead:
            - key: true
              name: 'inv'
              caption: "<%= _('lbl|invoice number') %>"
              label: null
              sortable: true
              hidden: false
              action: 'expand'
            - key: true
              name: 'due_date'
              caption: "<%= _('lbl|due date') %>"
              label: null
              sortable: true
              hidden: false
            - key: true
              name: 'amnt'
              caption: "<%= _('lbl|net value') %>"
              label: null
              sortable: true
              hidden: false
