title: "Open items"
components:
  - uuid: "open_items_table"
    description: "Fields with an asterisk (*) are mandatory."
    title: Open items
    type: datatable
    data_url: "/v1/open_items"
    elements:
      thead:
        - key: true
          name: 'inv'
          caption: 'Invoice'
          label: null
          sortable: true
          hidden: false
          action: 'expand'
        - key: true
          name: 'bill_date'
          caption: 'Due date'
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'net_value'
          caption: 'Total'
          label: null
          sortable: true
          hidden: false
