title: "Sold-to modal"
components:
  - uuid: "admin_user_partners_modal_form"
    description:
    method: GET
    title:
    type: form
    url: "/v1/partners"
    elements:
      - - atom: text
          label: Number
          name: "number"
          uuid: "number"
          placeholder: Number
          validation_type: string
          value: ""

      - - atom: text
          label: Name
          name: "name"
          uuid: "name"
          placeholder: Name
          value: ""

      - - atom: text
          label: City
          name: "city"
          uuid: "city"
          placeholder: City
          value: ""

        - atom: text
          label: Postal Code
          name: "postal_code"
          uuid: "postal_code"
          placeholder: Postal Code
          value: ""


      - - atom: button
          text: Cancel
          type: text
          action_type: button

        -
          atom: button
          text: Apply
          type: secondary
          action_type: submit
