title: "Select Sold-to/Ship-to"
components:
  - uuid: "search_salesdoc_table"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Select sold-to`s
    type: datatable
    url: "/v1/partners"
    elements:
      thead:
        - key: true
          name: 'nr'
          caption: 'Number'
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'name1'
          caption: 'Name'
          label: null
          sortable: true
          hidden: false
        - name: 'city'
          caption: 'City'
          label: null
          sortable: true
          hidden: false
        - name: 'postal_code'
          caption: 'Postal code'
          label: null
          sortable: true
          hidden: false
        - name: 'action'
          caption: 'Action'
          label: null
          sortable: false
          hidden: false
          row_action: "Add"
          type_btn: "secondary"
