title: "<%= _('page title|search for partners') %>"
components:
  - uuid: "admin_user_partners_modal_form"
    description:
    method: GET
    title:
    type: form
    url: "/v1/partners"
    elements:
      - - atom: text
          label: "<%= _('lbl|partner number') %>"
          name: "number"
          uuid: "number"
          placeholder: "<%= _('plc|partner number') %>"
          validation_type: string
          value: ""

      - - atom: text
          label: "<%= _('lbl|partner name') %>"
          name: "name"
          uuid: "name"
          placeholder: "<%= _('plc|partner name') %>"
          value: ""

      - - atom: text
          label: "<%= _('lbl|city') %>"
          name: "city"
          uuid: "city"
          placeholder: "<%= _('plc|city') %>"
          value: ""

        - atom: text
          label: "<%= _('lbl|postal code') %>"
          name: "postal_code"
          uuid: "postal_code"
          placeholder: "<%= _('plc|postal code') %>"
          value: ""


      - - atom: button
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        -
          atom: button
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit
