title: "<%= _('page title|search for payments') %>"
components:
  - uuid: "search_payments_table"
    method: POST
    type: datatable
    data_url: "/v1/payments"
    elements:
      thead:
        - key: true
          name: 'payment_number'
          caption: "<%= _('lbl|payment number') %>"
          label: null
          sortable: true
          hidden: false
          action: 'link'
        - key: true
          name: 'payment_date'
          caption: "<%= _('lbl|payment date') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'amount_in_doc_currency'
          caption: "<%= _('lbl|amount in doc currency') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'doc_currency'
          caption: "<%= _('lbl|doc currency') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'assignment_number'
          caption: "<%= _('lbl|assignment number') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'debit_or_credit'
          caption: "<%= _('lbl|debit or credit') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'fiscal_year'
          caption: "<%= _('lbl|fiscal year') %>"
          label: null
          sortable: true
          hidden: true
