title: "<%= _('page title|search for payments') %>"
components:
  - uuid: "search_payments_table"
    method: POST
    type: datatable
    data_url: "/v1/payments"
    elements:
      thead:
        - key: true
          name: 'doc_number'
          caption: "<%= _('lbl|doc number') %>"
          label: null
          sortable: true
          hidden: false
          action: 'link'
        - key: true
          name: 'doc_type'
          caption: "<%= _('lbl|doc type') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'doc_date'
          caption: "<%= _('lbl|doc date') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'po_number'
          caption: "<%= _('lbl|po') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'ship_status'
          caption: "<%= _('lbl|ship status') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'net_value'
          caption: "<%= _('lbl|net value') %>"
          label: null
          sortable: true
          hidden: false
        - key: true
          name: 'sold_to_number'
          caption: "<%= _('lbl|sold to number') %>"
          label: null
          sortable: true
          hidden: true
        - key: true
          name: 'sold_to_description'
          caption: "<%= _('lbl|sold to descr') %>"
          label: null
          sortable: true
          hidden: true
