title: "<%= _('title|filter') %>"
components:
  - uuid: "filter_payment_modal_form"
    description:
    method: GET
    title: ""
    type: form
    url: "/v1/payments"
    elements:
      - - atom: select
          label: "<%= _('lbl|payer number') %>"
          name: "payer_number"
          uuid: "payer_number"
          placeholder: "<%= _('plc|payer number') %>"
          validation_type: string
          options: []
          validations:
            - message: "<%= _('error|attributes.payer_number.blank') %>"
              type: required
              value: ""

        - atom: text
          label: "<%= _('lbl|company code') %>"
          name: "comp_code"
          uuid: "comp_code"
          placeholder: "<%= _('plc|company code') %>"
          value: ""
          validations:
            - message: "<%= _('error|attributes.comp_code.blank') %>"
              type: required
              value: ""

      - - atom: date
          uuid: "from_date"
          label: "<%= _('lbl|from date') %>"
          name: "from_date"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.from_date.blank') %>"
              type: required
              value: ""

        - atom: date
          uuid: "to_date"
          label: "<%= _('lbl|to date') %>"
          name: "to_date"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.to_date.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "from_amount"
          label: "<%= _('lbl|from amount') %>"
          name: "from_amount"
          validation_type: string
          value: "0.0"

        - atom: text
          uuid: "to_amount"
          label: "<%= _('lbl|to amount') %>"
          name: "to_amount"
          validation_type: string
          value: "0.0"

      - - atom: button
          text: "<%= _('btn|cancel') %>"
          type: text
          uuid: "cancel"
          action_type: button

        - atom: button
          text: "<%= _('btn|apply') %>"
          type: secondary
          action_type: submit
