title: "<%= _('page title|registration') %>"
components:
  - uuid: "registration_form"
    description: "Fields with an asterisk (*) are mandatory."
    method: POST
    title: Registration
    type: form
    url: "/v1/registrations"
    elements:
      - - atom: text
          uuid: "first_name"
          label: "<%= _('lbl|first name') %>"
          name: "first_name"
          placeholder: "<%= _('plc|first name') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.first_name.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.first_name.to_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.first_name.too_long') %>"
              type: max
              value: "20"

      - - atom: text
          uuid: "last_name"
          label: "<%= _('lbl|last name') %>"
          name: "last_name"
          placeholder: "<%= _('plc|last name') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.last_name.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.last_name.to_short') %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.last_name.too_long') %>"
              type: max
              value: "20"

      - - atom: text
          uuid: "email"
          label: "<%= _('lbl|email address') %>"
          name: "email"
          placeholder: "<%= _('plc|email address') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.email.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "customer_number"
          label: "<%= _('lbl|customer number') %>"
          name: "customer_number"
          placeholder: "<%= _('plc|customer number') %>"
          validation_type: string
          value: ""

      - - atom: select
          uuid: "microsite_id"
          label: "<%= _('lbl|microsite') %>"
          name: "microsite_id"
          placeholder: "<%= _('plc|select microsite') %>"
          validation_type: string
          value: ""
          options:
            - name: "<%= _('lbl|microsite 1') %>"
              value: 'b2b_microsite1'
            - name: "<%= _('lbl|microsite 2') %>"
              value: 'b2b_client'
          validations:
            - message: "<%= _('error|attributes.microsite.blank') %>"
              type: required
              value: ""
      - - atom: select
          uuid: "language"
          label: "<%= _('lbl|language') %>"
          name: "language"
          placeholder: "<%= _('plc|select language') %>"
          validation_type: string
          value: ""
          options:
            - name: "<%= _('lbl|language en_US') %>"
              value: en_US
            - name: "<%= _('lbl|language pl_PL') %>"
              value: pl_PL
          validations:
            - message: "<%= _('error|attributes.language.blank') %>"
              type: required
              value: ""

      - - atom: text
          uuid: "company_name"
          label: "<%= _('lbl|company name') %>"
          name: "company_name"
          placeholder: "<%= _('plc|company name') %>"
          validation_type: string
          value: ""

      - - atom: text
          uuid: "street"
          label: "<%= _('lbl|street') %>"
          name: "street"
          placeholder: "<%= _('plc|street') %>"
          validation_type: string
          value: ""

      - - atom: text
          uuid: "phone"
          label: "<%= _('lbl|phone') %>"
          name: "phone"
          placeholder: "<%= _('plc|phone') %>"
          validation_type: string
          value: ""

      - - atom: text
          uuid: "city"
          label: "<%= _('lbl|city') %>"
          name: "city"
          placeholder: "<%= _('plc|city') %>"
          validation_type: string
          value: ""

      - - atom: button
          uuid: "Submit"
          text: "<%= _('btn|submit registration') %>"
          type: primary
          action_type: submit
