title: "<%= _('title|have a question') %>"
components:
  - uuid: "salesdocs_questions_create_form"
    description:
    method: POST
    title: "<%= _('title|contact about salesdoc') %>"
    type: form
    url: "/v1/salesdocs/<%= @object[:salesdoc_doc_number] %>/questions"
    elements:
      - - atom: text
          uuid: "text"
          label: "<%= _('lbl|your message') %>"
          name: "text"
          placeholder: "<%= _('plc|your message') %>"
          validation_type: string
          value: ""
          validations:
            - message: "<%= _('error|attributes.text.blank') %>"
              type: required
              value: ""
            - message: "<%= _('error|attributes.text.min_max') % { min: 3, max: 1000 } %>"
              type: min
              value: "3"
            - message: "<%= _('error|attributes.text.min_max') % { min: 3, max: 1000 } %>"
              type: max
              value: "1000"

      - - atom: button
          text: "<%= _('btn|cancel') %>"
          type: text
          action_type: button

        - atom: button
          text: "<%= _('btn|send email') %>"
          type: secondary
          action_type: submit
