title: "Filter"
components:
  - uuid: "filter_salesdocs_modal_form"
    description:
    method: GET
    title:
    type: form
    url: "/v1/salesdocs"
    elements:
      - - atom: select
          uuid: "search_option"
          label: Search Criteria
          name: "search_criteria"
          placeholder: Select Search Criteria
          validation_type: string
          value: ""
          options:
            - name: Sold to number
              value: "sold_to_number"
            - name: Ship to number
              value: "ship_to_number"
            - name: PO number
              value: "po_number"
            - name: Material number
              value: "material"
            - name: Invoice number
              value: "invoice_number"
            - name: Delivery number
              value: "delivery_number"

        - atom: text
          uuid: "search_criteria_value"
          label: Search Criteria Value
          name: "search_criteria_value"
          value: ""

      - - atom: date
          label: From date
          name: "from_date"
          value: ""

        - atom: date
          label: To date
          name: "to_date"
          value: ""

      - - atom: select
          label: Status
          uuid: "status"
          name: "status"
          value: "ALL"
          options:
            - name: All
              value: "ALL"
            - name: Not shipped
              value: "NSHP"
            - name: Shipped
              value: "SHIP"

      - - atom: button
          text: Cancel
          type: text
          action_type: button
          name: "apply"

        - atom: button
          text: Apply
          type: secondary
          action_type: submit
          name: "apply"
