title: "Login page"
components:
  - uuid: "login_form"
    description: "Please enter username and password"
    method: POST
    title: Login
    type: form
    url: "/v1/auth"
    elements:
      - - atom: text
          uuid: 'username'
          label: Username
          name: "username"
          placeholder: Username
          value: ""
          validation_type: string
          validations:
            - message: "<%= I18n.t('activemodel.errors.models.attributes.username.blank') %>"
              type: required
              value: ""
            - message: "<%= I18n.t('activemodel.errors.models.attributes.username.too_short') %>"
              type: min
              value: "3"
            - message: "<%= I18n.t('activemodel.errors.models.attributes.username.too_long') %>"
              type: max
              value: "25"
      - - atom: password
          uuid: "password"
          label: Password
          name: "password"
          placeholder: Password
          validation_type: string
          value: ""
          validations:
            - message: "<%= I18n.t('activemodel.errors.models.attributes.password.blank') %>"
              type: required
              value: ""
            - message: "<%= I18n.t('activemodel.errors.models.attributes.password.too_short') %>"
              type: min
              value: "3"
            - message: "<%= I18n.t('activemodel.errors.models.attributes.password.too_long') %>"
              type: max
              value: "20"
      - - atom: button
          uuid: "button_1"
          text: Login
          type: primary
          action_type: submit
        - atom: link
          uuid: "link_1"
          button_like: "false"
          path: /password/reset
          text: "Forgot your password?"
      - - atom: link
          uuid: "link_2"
          button_like: "true"
          type: "secondary"
          path: /registration
          text: "Create an account"
