default: &default
  adapter: mysql2
  encoding: utf8
  host: mysql
  username: root
  password:

development:
  <<: *default
  database: corevist_api_dev

qa:
  <<: *default
  database: corevist_api_dev

test:
  <<: *default
  database: corevist_api_test
