number_format_US: '.,'
date_format_US: '%m/%d/%Y'
locales:
  - en_US
  - es_ES
  - ru_RU
  - de_DE
#  - fr_CA
#  - fr_FR
#  - nl_BE
#  - nl_NL
#  - sv_SE
#  - zh_CN
#  - cs_CZ
#  - da_DK
#  - en_GB
#  - it_IT
#  - nb_NO
#  - pl_PL
#  - pt_BR
#  - pt_PT
#  - tr_TR

timezones:
  est: est
  utc: utc

number_formats:
  en_US: '.,'
  de_DE: ',.'
  ar_EG: ".'"
  fr_FR: ", "

time_formats:
  24h: '%H:%M:%S'
  12h: '%I:%M:%S %p'

date_formats:
  US: '%m/%d/%Y'
  EU: '%d.%m.%Y'
  CI: '%Y/%m/%d'
  SW: '%Y-%m-%d'

decimals:
  JPY: 0
  HUF: 0
  TRL: 0
  COP: 0
  IDR: 0
  KRW: 0
  '%': 3
  USD: 2
  EUR: 2

self_url: http://localhost:3001
