username:
  presence: true
first_name:
  presence: true
last_name:
  presence: true
email:
  presence: true
phone:
  presence: true
password:
  presence: true
confirm_password:
  presence: true
microsite_id:
  presence: true
user_type_id:
  presence: true
language:
  presence: true
time_zone:
  presence: true
number_format:
  presence: true
date_format:
  presence: true
time_format:
  presence: true
user_classification_id:
  presence: true
