id:
  presence: true
username: {}
first_name: {}
last_name: {}
email: {}
phone: {}
password: {}
confirm_password: {}
microsite_id: {}
user_type_id: {}
language: {}
time_zone: {}
number_format: {}
date_format: {}
time_format: {}
user_classification_id: {}
role_ids:
  array: true
assignable_role_ids:
  array: true
partners:
  array_of_hashes:
    fields: ['number', 'function']
territories_ids:
  array: true
