module Sap::Tables
  CUSTOM_TABLES = 'CUSTOM_TABLES'.freeze
  USER_DATA = 'USER_DATA'.freeze
  ASSIGNED_SOLD_TOS = 'ASSIGNED_SOLD_TOS'.freeze
  ASSIGNED_SHIP_TOS = 'ASSIGNED_SHIP_TOS'.freeze
  ASSIGNED_PAYERS = 'ASSIGNED_PAYERS'.freeze
  ASSIGNED_TERRITORIES = 'ASSIGNED_TERRITORIES'.freeze
  ASSIGNED_SALES_AREAS = 'ASSIGNED_SALES_AREAS'.freeze
  SEARCH_CRITERIA = 'SEARCH_CRITERIA'.freeze
  SALES_DOCUMENTS = 'SALES_DOCUMENTS'.freeze
  SHIPMENTS = 'SHIPMENTS'.freeze
end
